name: alembic
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  system_tray: ^2.0.3
  screen_retriever: ^0.2.0
  flutter_acrylic: ^1.1.4
  github: ^9.24.0
  git: ^2.3.0
  hive_flutter: ^1.1.0
  pylon: ^3.1.3
  toxic: ^1.3.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  fast_log: ^1.0.7
  flutter_svg: ^2.0.16
  padded: ^1.0.1
  crypto: ^3.0.6
  encrypt: ^5.0.3
  oauth2: ^2.0.3
  arcane: ^3.7.2
dependency_overrides: 
  uuid: ^4.4.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
