name: alembic
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.9
environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  tray_manager: ^0.3.1
  screen_retriever: ^0.2.0
  flutter_acrylic: ^1.1.4
  github: ^9.24.0
  git: ^2.3.0
  hive_flutter: ^1.1.0
  pylon: ^3.1.9
  toxic: ^1.3.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  fast_log: ^1.0.7
  flutter_svg: ^2.0.16
  padded: ^1.0.1
  crypto: ^3.0.6
  encrypt: ^5.0.3
  oauth2: ^2.0.3
  arcane: ^3.10.11
  launch_at_startup: ^0.3.1
  package_info_plus: ^8.1.2
  http: ^1.2.2
  file_picker: ^8.1.6
dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  shaders:
    - packages/arcane/resources/shaders/frost.frag
    - packages/arcane/resources/shaders/pixelate.frag
    - packages/arcane/resources/shaders/pixelate_blur.frag
    - packages/arcane/resources/shaders/rgb.frag
    - packages/arcane/resources/shaders/loader.frag
    - packages/arcane/resources/shaders/glyph.frag
    - packages/arcane/resources/shaders/invert.frag
    - packages/arcane/resources/shaders/warp.frag
    - packages/arcane/resources/shaders/black_hole.frag
    - packages/arcane/resources/shaders/lux.frag
    - packages/arcane/resources/shaders/cascade.frag
  uses-material-design: true
  assets:
    - assets/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/launcher.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: true
    image_path: "assets/launcher.png"
scripts:
  codesign: cd build/macos/Build/Products/Release && codesign --deep --force --verify --sign "Alembic" alembic.app
  launcher_icons: flutter pub get && dart run flutter_launcher_icons
  distrib: grep '^version:' pubspec.yaml | sed -E 's/^version:\s*//; s/^[[:space:]]+//; s/[[:space:]]+$//' > version && rm -rf dist && dart pub global activate flutter_distributor && npm install -g appdmg && flutter_distributor package --platform macos --targets dmg --skip-clean